const MODEL = {
  global_constants: {
    skill_match_multiplier: 1.25,
    skill_mismatch_multiplier: 1.0,
    level_formula_divisor: 50,
    perk_multipliers: { 0: 1.0, 1: 1.05, 2: 1.1, 3: 1.15 },
    required_tool_limit: { "槌全般": 2.0, "小刀全般": 1.75, "近接武器": 3.0, "遠距離武器": 2.5, "彫刻刀": 1.0, "桶": 1.0, "漁網": 1.0, "釣り竿類": 1.5, "武器全般": 3.0, "つるはし全般": 1.75, "釿全般": 1.75, "斧全般": 1.75, "攪拌道具": 1.0, "種": 1.0 }
  },
  recipes: {
    "衛兵_近接武器": { base_cost0_num: 10, base_cost0_den: 1 },
    "衛兵_遠距離武器": { base_cost0_num: 10, base_cost0_den: 1 },
    "物見やぐら_専用": { base_cost0_num: 1, base_cost0_den: 2 },
    "灯籠夫_灯台": { base_cost0_num: 2, base_cost0_den: 1 },
    "神主_鐘楼": { base_cost0_num: 5, base_cost0_den: 1 },
    "神主_手水舎": { base_cost0_num: 1, base_cost0_den: 1 },
    "神主_小社": { base_cost0_num: 20, base_cost0_den: 1 },
    "神主_中社": { base_cost0_num: 20, base_cost0_den: 2 },
    "神主_大社": { base_cost0_num: 20, base_cost0_den: 3 },
    "水_シンプル井戸": { base_cost0_num: 4, base_cost0_den: 5 },
    "水_上級井戸": { base_cost0_num: 4, base_cost0_den: 6 },
    "水_大井戸": { base_cost0_num: 4, base_cost0_den: 10 },
    "茶室_茶会": { base_cost0_num: 2, base_cost0_den: 1 },
    "酒場の主人(水x2)": { base_cost0_num: 2, base_cost0_den: 1 },
    "酒場の主人(水x1+アルコールを含まない飲料全般x1)": { base_cost0_num: 2, base_cost0_den: 1 },
    "酒場の主人(水x1+アルコール飲料全般x1)": { base_cost0_num: 2, base_cost0_den: 1 },
    "天ぷら_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "天ぷら_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "調理したゴボウ_酒場の調理場": { base_cost0_num: 1, base_cost0_den: 1 },
    "調理したゴボウ_台所の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "調理したゴボウ_囲炉裏と調理鍋の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "調理したゴボウ_囲炉裏の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "調理した魚_酒場の調理場": { base_cost0_num: 1, base_cost0_den: 1 },
    "調理した魚_台所の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "調理した魚_囲炉裏と調理鍋の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "調理した魚_囲炉裏の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "炊いた米_酒場の調理場": { base_cost0_num: 1, base_cost0_den: 1 },
    "炊いた米_台所の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "炊いた米_囲炉裏と調理鍋の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "干し果実_酒場の調理場": { base_cost0_num: 3, base_cost0_den: 4 },
    "干し果実_台所の調理場": { base_cost0_num: 15, base_cost0_den: 16 },
    "干し果実_囲炉裏と調理鍋の仕事場": { base_cost0_num: 3, base_cost0_den: 2 },
    "干し果実_囲炉裏の仕事場": { base_cost0_num: 3, base_cost0_den: 2 },
    "蜂蜜漬け果実_酒場の調理場": { base_cost0_num: 1, base_cost0_den: 1 },
    "蜂蜜漬け果実_台所の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "油(魚)_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "油(魚)_台所の調理場": { base_cost0_num: 25, base_cost0_den: 16 },
    "油(魚)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 2 },
    "油_搾油": { base_cost0_num: 4, base_cost0_den: 5 },
    "枝_採集者の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "卵_採集者の仕事場": { base_cost0_num: 3, base_cost0_den: 2 },
    "樹皮_採集者の仕事場": { base_cost0_num: 1, base_cost0_den: 1 },
    "梶の樹皮_採集者の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "柚子の果実_採集者の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "ゴボウ_採集者の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "菊の花_採集者の仕事場": { base_cost0_num: 3, base_cost0_den: 10 },
    "彼岸花_採集者の仕事場": { base_cost0_num: 3, base_cost0_den: 10 },
    "えのき_採集者の仕事場": { base_cost0_num: 13, base_cost0_den: 10 },
    "舞茸_採集者の仕事場": { base_cost0_num: 13, base_cost0_den: 10 },
    "松茸_採集者の仕事場": { base_cost0_num: 13, base_cost0_den: 10 },
    "しいたけ_採集者の仕事場": { base_cost0_num: 13, base_cost0_den: 10 },
    "ベニテングダケ_採集者の仕事場": { base_cost0_num: 7, base_cost0_den: 10 },
    "カエンタケ_採集者の仕事場": { base_cost0_num: 7, base_cost0_den: 10 },
    "ヒョウタンノキの実_採集者の仕事場": { base_cost0_num: 23, base_cost0_den: 10 },
    "わさび_採集者の仕事場": { base_cost0_num: 5, base_cost0_den: 2 },
    "ニンニク_採集者の仕事場": { base_cost0_num: 5, base_cost0_den: 2 },
    "三つ葉_採集者の仕事場": { base_cost0_num: 5, base_cost0_den: 2 },
    "木苺_採集者の仕事場": { base_cost0_num: 3, base_cost0_den: 5 },
    "コケモモ_採集者の仕事場": { base_cost0_num: 3, base_cost0_den: 5 },
    "プラム_採集者の仕事場": { base_cost0_num: 3, base_cost0_den: 2 },
    "茶(酒場の調理場版)_酒場の調理場": { base_cost0_num: 3, base_cost0_den: 4 },
    "茶(酒場の調理場版)_台所の調理場": { base_cost0_num: 15, base_cost0_den: 16 },
    "茶(酒場の調理場版)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 3, base_cost0_den: 2 },
    "お粥_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "果実汁_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "野菜汁_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "亀汁_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "亀汁_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "味噌汁_酒場の調理場": { base_cost0_num: 1, base_cost0_den: 1 },
    "味噌汁_台所の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "味噌_酒場の調理場": { base_cost0_num: 1, base_cost0_den: 1 },
    "具沢山味噌汁_酒場の調理場": { base_cost0_num: 1, base_cost0_den: 1 },
    "具沢山味噌汁_台所の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "鍋_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "鍋_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "お粥_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "果実汁_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "野菜汁_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な魚料理(魚1+豆全般5)_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "質素な魚料理(魚1+豆全般5)_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な魚料理(魚1+豆全般5)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "質素な魚料理(魚1+食用キノコ全般1)_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "質素な魚料理(魚1+食用キノコ全般1)_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な魚料理(魚1+食用キノコ全般1)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "きちんとした魚料理(魚2+薬草全般3+穀物全般1)_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 2 },
    "きちんとした魚料理(魚2+薬草全般3+穀物全般1)_台所の調理場": { base_cost0_num: 25, base_cost0_den: 8 },
    "きちんとした魚料理(魚2+薬草全般3+穀物全般1)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 1 },
    "きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1)_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 2 },
    "きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1)_台所の調理場": { base_cost0_num: 25, base_cost0_den: 8 },
    "きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 1 },
    "豪華な魚料理(魚1+穀物全般5+豆全般10)_酒場の調理場": { base_cost0_num: 15, base_cost0_den: 4 },
    "豪華な魚料理(魚2+お米7+薬草全般2)_酒場の調理場": { base_cost0_num: 15, base_cost0_den: 4 },
    "なれずし_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "なれずし_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な肉料理(肉1+穀物全般6)_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "質素な肉料理(肉1+穀物全般6)_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な肉料理(肉1+穀物全般6)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "質素な肉料理(肉1+食用キノコ全般1)_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "質素な肉料理(肉1+食用キノコ全般1)_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な肉料理(肉1+食用キノコ全般1)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "質素な肉料理(肉1+豆全般5)_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "質素な肉料理(肉1+豆全般5)_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な肉料理(肉1+豆全般5)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "きちんとした肉料理(肉1+卵1+豆全般6)_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 2 },
    "きちんとした肉料理(肉1+卵1+豆全般6)_台所の調理場": { base_cost0_num: 25, base_cost0_den: 8 },
    "きちんとした肉料理(肉1+卵1+豆全般6)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 1 },
    "きちんとした肉料理(肉2+薬草全般2+穀物全般1)_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 2 },
    "きちんとした肉料理(肉2+薬草全般2+穀物全般1)_台所の調理場": { base_cost0_num: 25, base_cost0_den: 8 },
    "きちんとした肉料理(肉2+薬草全般2+穀物全般1)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 1 },
    "きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6)_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 2 },
    "きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6)_台所の調理場": { base_cost0_num: 25, base_cost0_den: 8 },
    "きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 1 },
    "豪華な肉料理(肉2+穀物全般4+豆全般4)_酒場の調理場": { base_cost0_num: 15, base_cost0_den: 4 },
    "豪華な肉料理(肉2+お米5+薬草全般3)_酒場の調理場": { base_cost0_num: 15, base_cost0_den: 4 },
    "豪華な肉料理(肉1+お米4+食用キノコ全般2)_酒場の調理場": { base_cost0_num: 15, base_cost0_den: 4 },
    "焼き鳥_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "質素な野菜料理(野菜全般5+豆全般3)_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "質素な野菜料理(野菜全般5+薬草全般3)_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "質素な野菜料理(野菜全般4+食用キノコ全般1)_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "きちんとした野菜料理(大豆10+麹2)_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 2 },
    "きちんとした野菜料理(水1+穀物全般6+果実全般3)_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 2 },
    "きちんとした野菜料理(水1+豆全般6+薬草全般3)_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 2 },
    "豪華な野菜料理(穀物全般7+油1+水1+サトイモ8)_酒場の調理場": { base_cost0_num: 15, base_cost0_den: 4 },
    "豪華な野菜料理(お米12+しいたけ2+ネギ5+油1)_酒場の調理場": { base_cost0_num: 15, base_cost0_den: 4 },
    "豪華な野菜料理(小麦7+野菜全般8+わさび3+油1)_酒場の調理場": { base_cost0_num: 15, base_cost0_den: 4 },
    "豆腐_酒場の調理場": { base_cost0_num: 1, base_cost0_den: 1 },
    "田楽_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "田楽_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "焼き鳥_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "味噌_台所の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "豆腐_台所の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "質素な野菜料理(野菜全般5+豆全般3)_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な野菜料理(野菜全般5+豆全般3)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "質素な野菜料理(野菜全般5+豆全般3)_囲炉裏の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "質素な野菜料理(野菜全般5+薬草全般3)_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な野菜料理(野菜全般5+薬草全般3)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "質素な野菜料理(野菜全般5+薬草全般3)_囲炉裏の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "質素な野菜料理(野菜全般4+食用キノコ全般1)_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "質素な野菜料理(野菜全般4+食用キノコ全般1)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "きちんとした野菜料理(大豆10+麹2)_台所の調理場": { base_cost0_num: 25, base_cost0_den: 8 },
    "きちんとした野菜料理(大豆10+麹2)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 1 },
    "きちんとした野菜料理(水1+穀物全般6+果実全般3)_台所の調理場": { base_cost0_num: 25, base_cost0_den: 8 },
    "きちんとした野菜料理(水1+穀物全般6+果実全般3)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 1 },
    "きちんとした野菜料理(水1+豆全般6+薬草全般3)_台所の調理場": { base_cost0_num: 25, base_cost0_den: 8 },
    "きちんとした野菜料理(水1+豆全般6+薬草全般3)_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 1 },
    "甘酒_酒場の調理場": { base_cost0_num: 9, base_cost0_den: 10 },
    "甘酒_台所の調理場": { base_cost0_num: 9, base_cost0_den: 8 },
    "甘酒_囲炉裏と調理鍋の仕事場": { base_cost0_num: 9, base_cost0_den: 5 },
    "甘酒_囲炉裏の仕事場": { base_cost0_num: 9, base_cost0_den: 5 },
    "どぶろく_酒場の調理場": { base_cost0_num: 3, base_cost0_den: 5 },
    "どぶろく_台所の調理場": { base_cost0_num: 3, base_cost0_den: 4 },
    "どぶろく_囲炉裏と調理鍋の仕事場": { base_cost0_num: 6, base_cost0_den: 5 },
    "どぶろく_囲炉裏の仕事場": { base_cost0_num: 6, base_cost0_den: 5 },
    "調理した卵_酒場の調理場": { base_cost0_num: 1, base_cost0_den: 1 },
    "調理した卵_台所の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "調理した卵_囲炉裏と調理鍋の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "調理した卵_囲炉裏の仕事場": { base_cost0_num: 2, base_cost0_den: 1 },
    "団子_酒場の調理場": { base_cost0_num: 7, base_cost0_den: 4 },
    "団子_台所の調理場": { base_cost0_num: 35, base_cost0_den: 16 },
    "団子_囲炉裏と調理鍋の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "団子_囲炉裏の仕事場": { base_cost0_num: 7, base_cost0_den: 2 },
    "調理した肉_酒場の調理場": { base_cost0_num: 5, base_cost0_den: 4 },
    "調理した肉_台所の調理場": { base_cost0_num: 25, base_cost0_den: 16 },
    "調理した肉_囲炉裏と調理鍋の仕事場": { base_cost0_num: 5, base_cost0_den: 2 },
    "調理した肉_囲炉裏の仕事場": { base_cost0_num: 5, base_cost0_den: 2 },
    "生肉_猟師の仕事場": { base_cost0_num: 3, base_cost0_den: 1 },
    "脂肪_猟師の仕事場": { base_cost0_num: 5, base_cost0_den: 2 },
    "魚_漁師の仕事場": { base_cost0_num: 3, base_cost0_den: 2 },
    "魚_基本の釣り場": { base_cost0_num: 2, base_cost0_den: 1 },
    "魚_匠の釣り場": { base_cost0_num: 8, base_cost0_den: 5 },
    "魚_高度な釣り場": { base_cost0_num: 20, base_cost0_den: 11 },
    "治癒の飲料_調薬台": { base_cost0_num: 3, base_cost0_den: 1 },
    "治癒の包帯_調薬台": { base_cost0_num: 4, base_cost0_den: 1 },
    "治癒の軟膏_調薬台": { base_cost0_num: 4, base_cost0_den: 1 },
    "火傷軟膏_調薬台": { base_cost0_num: 4, base_cost0_den: 1 },
    "温かい飲み物_調薬台": { base_cost0_num: 3, base_cost0_den: 1 },
    "風邪薬_調薬台": { base_cost0_num: 4, base_cost0_den: 1 },
    "栄養剤_調薬台": { base_cost0_num: 5, base_cost0_den: 2 },
    "蚊よけ_調薬台": { base_cost0_num: 4, base_cost0_den: 1 },
    "冷たい飲み物_調薬台": { base_cost0_num: 5, base_cost0_den: 2 },
    "痛み止め_調薬台": { base_cost0_num: 4, base_cost0_den: 1 },
    "対毒調合薬_調薬台": { base_cost0_num: 15, base_cost0_den: 2 },
    "解毒薬_調薬台": { base_cost0_num: 25, base_cost0_den: 2 },
    "マラリア治療薬_調薬台": { base_cost0_num: 25, base_cost0_den: 2 },
    "果実の抽出液_調薬台": { base_cost0_num: 5, base_cost0_den: 1 },
    "プラムの抽出液_調薬台": { base_cost0_num: 5, base_cost0_den: 1 },
    "柚子の抽出液_調薬台": { base_cost0_num: 5, base_cost0_den: 1 },
    "兵糧丸_調薬台": { base_cost0_num: 5, base_cost0_den: 2 },
    "陶器_陶芸窯": { base_cost0_num: 2, base_cost0_den: 1 },
    "氷_鉱夫の仕事場": { base_cost0_num: 3, base_cost0_den: 2 },
    "蜂蜜_小さな蜜蜂の巣箱": { base_cost0_num: 13, base_cost0_den: 10 },
    "蜂蜜_大きな蜜蜂の巣箱": { base_cost0_num: 13, base_cost0_den: 20 },
    "藁_草の乾燥棚": { base_cost0_num: 2, base_cost0_den: 5 },
    "藁_ヤシの葉の乾燥棚": { base_cost0_num: 1, base_cost0_den: 1 },
    "彫刻した石_石工所": { base_cost0_num: 3, base_cost0_den: 1 },
    "天照大御神の像_石工所": { base_cost0_num: 10, base_cost0_den: 1 },
    "稲荷像_石工所": { base_cost0_num: 10, base_cost0_den: 1 },
    "地蔵像_石工所": { base_cost0_num: 10, base_cost0_den: 1 },
    "観音像_石工所": { base_cost0_num: 10, base_cost0_den: 1 },
    "龍神像_石工所": { base_cost0_num: 10, base_cost0_den: 1 },
    "恵比寿像_石工所": { base_cost0_num: 10, base_cost0_den: 1 },
    "天神像_石工所": { base_cost0_num: 10, base_cost0_den: 1 },
    "八幡像_石工所": { base_cost0_num: 10, base_cost0_den: 1 },
    "粘土_鉱夫の仕事場": { base_cost0_num: 4, base_cost0_den: 1 },
    "薪_大工作業台": { base_cost0_num: 3, base_cost0_den: 1 },
    "板(針葉樹)_大工作業台": { base_cost0_num: 3, base_cost0_den: 1 },
    "板(落葉樹)_大工作業台": { base_cost0_num: 3, base_cost0_den: 1 },
    "板(上質な針葉樹)_大工作業台": { base_cost0_num: 7, base_cost0_den: 2 },
    "板(上質な落葉樹)_大工作業台": { base_cost0_num: 7, base_cost0_den: 2 },
    "板(果樹)_大工作業台": { base_cost0_num: 4, base_cost0_den: 1 },
    "日本酒_圧力ろ過器": { base_cost0_num: 2, base_cost0_den: 1 },
    "焼酎_焼酎蒸留所": { base_cost0_num: 2, base_cost0_den: 1 },
    "ヒョウタンノキの水容器_仕立て台": { base_cost0_num: 15, base_cost0_den: 2 },
    "蓑_仕立て台": { base_cost0_num: 20, base_cost0_den: 1 },
    "木炭_炭窯": { base_cost0_num: 6, base_cost0_den: 5 },
    "小さな銅鑼_金敷": { base_cost0_num: 15, base_cost0_den: 2 },
    "鈴_金敷": { base_cost0_num: 6, base_cost0_den: 1 },
    "香炉_金敷": { base_cost0_num: 25, base_cost0_den: 2 },
    "儀式の鐘_金敷": { base_cost0_num: 3, base_cost0_den: 2 },
    "青銅の灯篭_金敷": { base_cost0_num: 6, base_cost0_den: 1 },
    "避難民の被り物_木工作業台": { base_cost0_num: 5, base_cost0_den: 1 },
    "避難民の被り物_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "木製の数珠_木工作業台": { base_cost0_num: 10, base_cost0_den: 1 },
    "真珠の数珠_木工作業台": { base_cost0_num: 20, base_cost0_den: 1 },
    "貝殻の数珠_木工作業台": { base_cost0_num: 25, base_cost0_den: 2 },
    "小さな御幣_木工作業台": { base_cost0_num: 3, base_cost0_den: 2 },
    "仏舎利塔のミニチュア_木工作業台": { base_cost0_num: 5, base_cost0_den: 1 },
    "竹玉_木工作業台": { base_cost0_num: 5, base_cost0_den: 1 },
    "玉串_木工作業台": { base_cost0_num: 3, base_cost0_den: 1 },
    "笛_木工作業台": { base_cost0_num: 7, base_cost0_den: 1 },
    "くし_木工作業台": { base_cost0_num: 10, base_cost0_den: 1 },
    "賽一式_木工作業台": { base_cost0_num: 15, base_cost0_den: 2 },
    "囲碁一式_木工作業台": { base_cost0_num: 25, base_cost0_den: 2 },
    "将棋一式_木工作業台": { base_cost0_num: 25, base_cost0_den: 1 },
    "双六一式_木工作業台": { base_cost0_num: 35, base_cost0_den: 2 },
    "小さな提燈_木工作業台": { base_cost0_num: 5, base_cost0_den: 1 },
    "小さな行燈_木工作業台": { base_cost0_num: 5, base_cost0_den: 1 },
    "円筒提燈_木工作業台": { base_cost0_num: 5, base_cost0_den: 1 },
    "油の行燈_木工作業台": { base_cost0_num: 5, base_cost0_den: 2 },
    "ろうそく_木工作業台": { base_cost0_num: 5, base_cost0_den: 1 },
    "竹のろうそく_木工作業台": { base_cost0_num: 5, base_cost0_den: 1 },
    "僧の服_仕立て台": { base_cost0_num: 7, base_cost0_den: 1 },
    "僧の被り物_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "天蓋_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "神主の装束_仕立て台": { base_cost0_num: 10, base_cost0_den: 1 },
    "冠_仕立て台": { base_cost0_num: 20, base_cost0_den: 1 },
    "僧兵の服_仕立て台": { base_cost0_num: 7, base_cost0_den: 1 },
    "深靴_仕立て台": { base_cost0_num: 6, base_cost0_den: 1 },
    "浪人笠_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "網代笠_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "革_なめし槽": { base_cost0_num: 5, base_cost0_den: 2 },
    "村人の服_仕立て台": { base_cost0_num: 7, base_cost0_den: 1 },
    "貴族の服_仕立て台": { base_cost0_num: 7, base_cost0_den: 1 },
    "盗賊の服_仕立て台": { base_cost0_num: 6, base_cost0_den: 1 },
    "靴下_仕立て台": { base_cost0_num: 4, base_cost0_den: 1 },
    "般若の面_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "田下駄_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "草鞋_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "農民の服_仕立て台": { base_cost0_num: 25, base_cost0_den: 2 },
    "天狗の面_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "藁帽子_仕立て台": { base_cost0_num: 4, base_cost0_den: 1 },
    "下駄_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "一本下駄_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "盗賊の被り物_仕立て台": { base_cost0_num: 4, base_cost0_den: 1 },
    "狐の面_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "翁の面_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "素朴な印籠_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "飾りつきの印籠_仕立て台": { base_cost0_num: 15, base_cost0_den: 2 },
    "匠の印籠_仕立て台": { base_cost0_num: 10, base_cost0_den: 1 },
    "足袋付きの草鞋_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "毛沓_仕立て台": { base_cost0_num: 25, base_cost0_den: 1 },
    "浅沓_仕立て台": { base_cost0_num: 10, base_cost0_den: 1 },
    "藁の輪_仕立て台": { base_cost0_num: 10, base_cost0_den: 1 },
    "裕福な商人の服_仕立て台": { base_cost0_num: 25, base_cost0_den: 1 },
    "軽量の侍の服_仕立て台": { base_cost0_num: 10, base_cost0_den: 1 },
    "商人の服(リネンx8)_仕立て台": { base_cost0_num: 7, base_cost0_den: 1 },
    "商人の服(リネンx20)_仕立て台": { base_cost0_num: 10, base_cost0_den: 1 },
    "養蜂家の枝細工の面_仕立て台": { base_cost0_num: 5, base_cost0_den: 1 },
    "養蜂家の被り物_仕立て台": { base_cost0_num: 20, base_cost0_den: 1 },
    "養蜂家の服_仕立て台": { base_cost0_num: 10, base_cost0_den: 1 },
    "烏天狗の面_仕立て台": { base_cost0_num: 6, base_cost0_den: 1 },
    "化け猫の面_仕立て台": { base_cost0_num: 6, base_cost0_den: 1 },
    "浪人の服_仕立て台": { base_cost0_num: 25, base_cost0_den: 1 },
    "工芸職人の服_仕立て台": { base_cost0_num: 10, base_cost0_den: 1 },
    "海賊の服_仕立て台": { base_cost0_num: 15, base_cost0_den: 2 },
    "紙_製紙場": { base_cost0_num: 2, base_cost0_den: 1 },
    "紙_製紙場(大)": { base_cost0_num: 2, base_cost0_den: 1 },
    "お米_水田": { base_cost0_num: 5, base_cost0_den: 1 },
    "カブ_畑": { base_cost0_num: 5, base_cost0_den: 1 },
    "サトイモ_水田": { base_cost0_num: 5, base_cost0_den: 1 },
    "ネギ_畑": { base_cost0_num: 5, base_cost0_den: 1 },
    "大豆_畑": { base_cost0_num: 5, base_cost0_den: 1 },
    "小麦_畑": { base_cost0_num: 5, base_cost0_den: 1 },
    "粟_畑": { base_cost0_num: 5, base_cost0_den: 1 },
    "菜種_畑": { base_cost0_num: 5, base_cost0_den: 1 },
    "ミョウガ_畑": { base_cost0_num: 5, base_cost0_den: 1 },
    "レンコン_水田": { base_cost0_num: 5, base_cost0_den: 1 }
  },
  categories: {
    "食事": {
      facilities: {
        "水田(お米)": { displayName: "水田", recipe: "お米_水田", recipeLabel: "稲作農業", facility_multiplier: 16, item_value: 1, tools: "種", land_size_max: 64 },
        "畑(カブ)": { displayName: "畑", recipe: "カブ_畑", recipeLabel: "カブ農業", facility_multiplier: 9, item_value: 2, tools: "種", land_size_max: 64 },
        "水田(サトイモ)": { displayName: "水田", recipe: "サトイモ_水田", recipeLabel: "サトイモ農業", facility_multiplier: 9, item_value: 2, tools: "種", land_size_max: 64 },
        "畑(ネギ)": { displayName: "畑", recipe: "ネギ_畑", recipeLabel: "ネギ農業", facility_multiplier: 9, item_value: 2, tools: "種", land_size_max: 64 },
        "畑(大豆)": { displayName: "畑", recipe: "大豆_畑", recipeLabel: "大豆農業", facility_multiplier: 16, item_value: 1, tools: "種", land_size_max: 64 },
        "畑(小麦)": { displayName: "畑", recipe: "小麦_畑", recipeLabel: "小麦農業", facility_multiplier: 16, item_value: 1, tools: "種", land_size_max: 64 },
        "畑(粟)": { displayName: "畑", recipe: "粟_畑", recipeLabel: "粟農業", facility_multiplier: 16, item_value: 1, tools: "種", land_size_max: 64 },
        "畑(菜種)": { displayName: "畑", recipe: "菜種_畑", recipeLabel: "キャノーラ農業", facility_multiplier: 9, item_value: 2, tools: "種", land_size_max: 64 },
        "畑(ミョウガ)": { displayName: "畑", recipe: "ミョウガ_畑", recipeLabel: "ミョウガ農業", facility_multiplier: 13, item_value: 1, tools: "種", land_size_max: 64 },
        "水田(レンコン)": { displayName: "水田", recipe: "レンコン_水田", recipeLabel: "蓮農業", facility_multiplier: 1, item_value: 3, tools: "種", land_size_max: 64 },
        "酒場の調理場(天ぷら)": { displayName: "酒場の調理場", recipe: "天ぷら_酒場の調理場", recipeLabel: "天ぷら", facility_multiplier: 1, item_value: 75, tools: "no" },
        "台所の調理場(天ぷら)": { displayName: "台所の調理場", recipe: "天ぷら_台所の調理場", recipeLabel: "天ぷら", facility_multiplier: 1, item_value: 75, tools: "no" },
        "酒場の調理場(調理したゴボウ)": { displayName: "酒場の調理場", recipe: "調理したゴボウ_酒場の調理場", recipeLabel: "調理したゴボウ", facility_multiplier: 1, item_value: 7, tools: "no" },
        "台所の調理場(調理したゴボウ)": { displayName: "台所の調理場", recipe: "調理したゴボウ_台所の調理場", recipeLabel: "調理したゴボウ", facility_multiplier: 1, item_value: 7, tools: "no" },
        "囲炉裏と調理鍋の仕事場(調理したゴボウ)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "調理したゴボウ_囲炉裏と調理鍋の仕事場", recipeLabel: "調理したゴボウ", facility_multiplier: 1, item_value: 7, tools: "no" },
        "囲炉裏の仕事場(調理したゴボウ)": { displayName: "囲炉裏の仕事場", recipe: "調理したゴボウ_囲炉裏の仕事場", recipeLabel: "調理したゴボウ", facility_multiplier: 1, item_value: 7, tools: "no" },
        "酒場の調理場(調理した魚)": { displayName: "酒場の調理場", recipe: "調理した魚_酒場の調理場", recipeLabel: "調理した魚", facility_multiplier: 1, item_value: 9, tools: "no" },
        "台所の調理場(調理した魚)": { displayName: "台所の調理場", recipe: "調理した魚_台所の調理場", recipeLabel: "調理した魚", facility_multiplier: 1, item_value: 9, tools: "no" },
        "囲炉裏と調理鍋の仕事場(調理した魚)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "調理した魚_囲炉裏と調理鍋の仕事場", recipeLabel: "調理した魚", facility_multiplier: 1, item_value: 9, tools: "no" },
        "囲炉裏の仕事場(調理した魚)": { displayName: "囲炉裏の仕事場", recipe: "調理した魚_囲炉裏の仕事場", recipeLabel: "調理した魚", facility_multiplier: 1, item_value: 9, tools: "no" },
        "酒場の調理場(炊いた米)": { displayName: "酒場の調理場", recipe: "炊いた米_酒場の調理場", recipeLabel: "炊いた米", facility_multiplier: 1, item_value: 24, tools: "no" },
        "台所の調理場(炊いた米)": { displayName: "台所の調理場", recipe: "炊いた米_台所の調理場", recipeLabel: "炊いた米", facility_multiplier: 1, item_value: 24, tools: "no" },
        "囲炉裏と調理鍋の仕事場(炊いた米)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "炊いた米_囲炉裏と調理鍋の仕事場", recipeLabel: "炊いた米", facility_multiplier: 1, item_value: 24, tools: "no" },
        "酒場の調理場(干し果実)": { displayName: "酒場の調理場", recipe: "干し果実_酒場の調理場", recipeLabel: "干し果実", facility_multiplier: 1, item_value: 7, tools: "no" },
        "台所の調理場(干し果実)": { displayName: "台所の調理場", recipe: "干し果実_台所の調理場", recipeLabel: "干し果実", facility_multiplier: 1, item_value: 7, tools: "no" },
        "囲炉裏と調理鍋の仕事場(干し果実)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "干し果実_囲炉裏と調理鍋の仕事場", recipeLabel: "干し果実", facility_multiplier: 1, item_value: 7, tools: "no" },
        "囲炉裏の仕事場(干し果実)": { displayName: "囲炉裏の仕事場", recipe: "干し果実_囲炉裏の仕事場", recipeLabel: "干し果実", facility_multiplier: 1, item_value: 7, tools: "no" },
        "酒場の調理場(蜂蜜漬け果実)": { displayName: "酒場の調理場", recipe: "蜂蜜漬け果実_酒場の調理場", recipeLabel: "蜂蜜漬け果実", facility_multiplier: 1, item_value: 20, tools: "no" },
        "台所の調理場(蜂蜜漬け果実)": { displayName: "台所の調理場", recipe: "蜂蜜漬け果実_台所の調理場", recipeLabel: "蜂蜜漬け果実", facility_multiplier: 1, item_value: 20, tools: "no" },
        "猟師の仕事場(生肉)": { displayName: "猟師の仕事場", recipe: "生肉_猟師の仕事場", recipeLabel: "生肉", facility_multiplier: 1, item_value: 5, tools: "小刀全般" },
        "猟師の仕事場(脂肪)": { displayName: "猟師の仕事場", recipe: "脂肪_猟師の仕事場", recipeLabel: "脂肪", facility_multiplier: 1, item_value: 5, tools: "小刀全般" },
        "漁師の仕事場(魚)": { displayName: "漁師の仕事場", recipe: "魚_漁師の仕事場", recipeLabel: "魚", facility_multiplier: 1, item_value: 4, tools: "漁網" },
        "基本の釣り場(魚)": { displayName: "基本の釣り場", recipe: "魚_基本の釣り場", recipeLabel: "魚", facility_multiplier: 1, item_value: 4, tools: "釣り竿類" },
        "匠の釣り場(魚)": { displayName: "匠の釣り場", recipe: "魚_匠の釣り場", recipeLabel: "魚", facility_multiplier: 1, item_value: 4, tools: "釣り竿類" },
        "高度な釣り場(魚)": { displayName: "高度な釣り場", recipe: "魚_高度な釣り場", recipeLabel: "魚", facility_multiplier: 1, item_value: 4, tools: "釣り竿類" },
        "酒場の調理場(調理した卵)": { displayName: "酒場の調理場", recipe: "調理した卵_酒場の調理場", recipeLabel: "調理した卵", facility_multiplier: 1, item_value: 6, tools: "no" },
        "台所の調理場(調理した卵)": { displayName: "台所の調理場", recipe: "調理した卵_台所の調理場", recipeLabel: "調理した卵", facility_multiplier: 1, item_value: 6, tools: "no" },
        "囲炉裏と調理鍋の仕事場(調理した卵)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "調理した卵_囲炉裏と調理鍋の仕事場", recipeLabel: "調理した卵", facility_multiplier: 1, item_value: 6, tools: "no" },
        "囲炉裏の仕事場(調理した卵)": { displayName: "囲炉裏の仕事場", recipe: "調理した卵_囲炉裏の仕事場", recipeLabel: "調理した卵", facility_multiplier: 1, item_value: 6, tools: "no" },
        "酒場の調理場(団子)": { displayName: "酒場の調理場", recipe: "団子_酒場の調理場", recipeLabel: "団子", facility_multiplier: 1, item_value: 32, tools: "no" },
        "台所の調理場(団子)": { displayName: "台所の調理場", recipe: "団子_台所の調理場", recipeLabel: "団子", facility_multiplier: 1, item_value: 32, tools: "no" },
        "採集者の仕事場(卵)": { displayName: "採集者の仕事場", recipe: "卵_採集者の仕事場", recipeLabel: "卵", facility_multiplier: 1, item_value: 3, tools: "no" },
        "酒場の調理場(お粥)": { displayName: "酒場の調理場", recipe: "お粥_酒場の調理場", recipeLabel: "お粥", facility_multiplier: 1, item_value: 27, tools: "no" },
        "台所の調理場(お粥)": { displayName: "台所の調理場", recipe: "お粥_台所の調理場", recipeLabel: "お粥", facility_multiplier: 1, item_value: 27, tools: "no" },
        "酒場の調理場(果実汁)": { displayName: "酒場の調理場", recipe: "果実汁_酒場の調理場", recipeLabel: "果実汁", facility_multiplier: 1, item_value: 25, tools: "no" },
        "台所の調理場(果実汁)": { displayName: "台所の調理場", recipe: "果実汁_台所の調理場", recipeLabel: "果実汁", facility_multiplier: 1, item_value: 25, tools: "no" },
        "酒場の調理場(野菜汁)": { displayName: "酒場の調理場", recipe: "野菜汁_酒場の調理場", recipeLabel: "野菜汁", facility_multiplier: 1, item_value: 30, tools: "no" },
        "台所の調理場(野菜汁)": { displayName: "台所の調理場", recipe: "野菜汁_台所の調理場", recipeLabel: "野菜汁", facility_multiplier: 1, item_value: 30, tools: "no" },
        "酒場の調理場(亀汁)": { displayName: "酒場の調理場", recipe: "亀汁_酒場の調理場", recipeLabel: "亀汁", facility_multiplier: 1, item_value: 95, tools: "no" },
        "台所の調理場(亀汁)": { displayName: "台所の調理場", recipe: "亀汁_台所の調理場", recipeLabel: "亀汁", facility_multiplier: 1, item_value: 95, tools: "no" },
        "酒場の調理場(味噌汁)": { displayName: "酒場の調理場", recipe: "味噌汁_酒場の調理場", recipeLabel: "味噌汁", facility_multiplier: 1, item_value: 55, tools: "no" },
        "台所の調理場(味噌汁)": { displayName: "台所の調理場", recipe: "味噌汁_台所の調理場", recipeLabel: "味噌汁", facility_multiplier: 1, item_value: 55, tools: "no" },
        "酒場の調理場(味噌)": { displayName: "酒場の調理場", recipe: "味噌_酒場の調理場", recipeLabel: "味噌", facility_multiplier: 1, item_value: 29, tools: "no" },
        "酒場の調理場(具沢山味噌汁)": { displayName: "酒場の調理場", recipe: "具沢山味噌汁_酒場の調理場", recipeLabel: "具沢山味噌汁", facility_multiplier: 1, item_value: 90, tools: "no" },
        "台所の調理場(具沢山味噌汁)": { displayName: "台所の調理場", recipe: "具沢山味噌汁_台所の調理場", recipeLabel: "具沢山味噌汁", facility_multiplier: 1, item_value: 90, tools: "no" },
        "酒場の調理場(鍋)": { displayName: "酒場の調理場", recipe: "鍋_酒場の調理場", recipeLabel: "鍋", facility_multiplier: 1, item_value: 95, tools: "no" },
        "台所の調理場(鍋)": { displayName: "台所の調理場", recipe: "鍋_台所の調理場", recipeLabel: "鍋", facility_multiplier: 1, item_value: 95, tools: "no" },
        "酒場の調理場(質素な魚料理(魚1+豆全般5))": { displayName: "酒場の調理場", recipe: "質素な魚料理(魚1+豆全般5)_酒場の調理場", recipeLabel: "質素な魚料理(魚1+豆全般5)", facility_multiplier: 1, item_value: 26, tools: "no" },
        "台所の調理場(質素な魚料理(魚1+豆全般5))": { displayName: "台所の調理場", recipe: "質素な魚料理(魚1+豆全般5)_台所の調理場", recipeLabel: "質素な魚料理(魚1+豆全般5)", facility_multiplier: 1, item_value: 26, tools: "no" },
        "囲炉裏と調理鍋の仕事場(質素な魚料理(魚1+豆全般5))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "質素な魚料理(魚1+豆全般5)_囲炉裏と調理鍋の仕事場", recipeLabel: "質素な魚料理(魚1+豆全般5)", facility_multiplier: 1, item_value: 26, tools: "no" },
        "酒場の調理場(質素な魚料理(魚1+食用キノコ全般1))": { displayName: "酒場の調理場", recipe: "質素な魚料理(魚1+食用キノコ全般1)_酒場の調理場", recipeLabel: "質素な魚料理(魚1+食用キノコ全般1)", facility_multiplier: 1, item_value: 26, tools: "no" },
        "台所の調理場(質素な魚料理(魚1+食用キノコ全般1))": { displayName: "台所の調理場", recipe: "質素な魚料理(魚1+食用キノコ全般1)_台所の調理場", recipeLabel: "質素な魚料理(魚1+食用キノコ全般1)", facility_multiplier: 1, item_value: 26, tools: "no" },
        "囲炉裏と調理鍋の仕事場(質素な魚料理(魚1+食用キノコ全般1))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "質素な魚料理(魚1+食用キノコ全般1)_囲炉裏と調理鍋の仕事場", recipeLabel: "質素な魚料理(魚1+食用キノコ全般1)", facility_multiplier: 1, item_value: 26, tools: "no" },
        "酒場の調理場(きちんとした魚料理(魚2+薬草全般3+穀物全般1))": { displayName: "酒場の調理場", recipe: "きちんとした魚料理(魚2+薬草全般3+穀物全般1)_酒場の調理場", recipeLabel: "きちんとした魚料理(魚2+薬草全般3+穀物全般1)", facility_multiplier: 1, item_value: 51, tools: "no" },
        "台所の調理場(きちんとした魚料理(魚2+薬草全般3+穀物全般1))": { displayName: "台所の調理場", recipe: "きちんとした魚料理(魚2+薬草全般3+穀物全般1)_台所の調理場", recipeLabel: "きちんとした魚料理(魚2+薬草全般3+穀物全般1)", facility_multiplier: 1, item_value: 51, tools: "no" },
        "囲炉裏と調理鍋の仕事場(きちんとした魚料理(魚2+薬草全般3+穀物全般1))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "きちんとした魚料理(魚2+薬草全般3+穀物全般1)_囲炉裏と調理鍋の仕事場", recipeLabel: "きちんとした魚料理(魚2+薬草全般3+穀物全般1)", facility_multiplier: 1, item_value: 51, tools: "no" },
        "酒場の調理場(きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1))": { displayName: "酒場の調理場", recipe: "きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1)_酒場の調理場", recipeLabel: "きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1)", facility_multiplier: 1, item_value: 51, tools: "no" },
        "台所の調理場(きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1))": { displayName: "台所の調理場", recipe: "きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1)_台所の調理場", recipeLabel: "きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1)", facility_multiplier: 1, item_value: 51, tools: "no" },
        "囲炉裏と調理鍋の仕事場(きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1)_囲炉裏と調理鍋の仕事場", recipeLabel: "きちんとした魚料理(魚1+薬草全般4+食用キノコ全般1)", facility_multiplier: 1, item_value: 51, tools: "no" },
        "酒場の調理場(豪華な魚料理(魚1+穀物全般5+豆全般10))": { displayName: "酒場の調理場", recipe: "豪華な魚料理(魚1+穀物全般5+豆全般10)_酒場の調理場", recipeLabel: "豪華な魚料理(魚1+穀物全般5+豆全般10)", facility_multiplier: 1, item_value: 70, tools: "no" },
        "酒場の調理場(豪華な魚料理(魚2+お米7+薬草全般2))": { displayName: "酒場の調理場", recipe: "豪華な魚料理(魚2+お米7+薬草全般2)_酒場の調理場", recipeLabel: "豪華な魚料理(魚2+お米7+薬草全般2)", facility_multiplier: 1, item_value: 70, tools: "no" },
        "酒場の調理場(なれずし)": { displayName: "酒場の調理場", recipe: "なれずし_酒場の調理場", recipeLabel: "なれずし", facility_multiplier: 1, item_value: 54, tools: "no" },
        "台所の調理場(なれずし)": { displayName: "台所の調理場", recipe: "なれずし_台所の調理場", recipeLabel: "なれずし", facility_multiplier: 1, item_value: 54, tools: "no" },
        "酒場の調理場(質素な肉料理(肉1+穀物全般6))": { displayName: "酒場の調理場", recipe: "質素な肉料理(肉1+穀物全般6)_酒場の調理場", recipeLabel: "質素な肉料理(肉1+穀物全般6)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "台所の調理場(質素な肉料理(肉1+穀物全般6))": { displayName: "台所の調理場", recipe: "質素な肉料理(肉1+穀物全般6)_台所の調理場", recipeLabel: "質素な肉料理(肉1+穀物全般6)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "囲炉裏と調理鍋の仕事場(質素な肉料理(肉1+穀物全般6))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "質素な肉料理(肉1+穀物全般6)_囲炉裏と調理鍋の仕事場", recipeLabel: "質素な肉料理(肉1+穀物全般6)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "酒場の調理場(質素な肉料理(肉1+食用キノコ全般1))": { displayName: "酒場の調理場", recipe: "質素な肉料理(肉1+食用キノコ全般1)_酒場の調理場", recipeLabel: "質素な肉料理(肉1+食用キノコ全般1)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "台所の調理場(質素な肉料理(肉1+食用キノコ全般1))": { displayName: "台所の調理場", recipe: "質素な肉料理(肉1+食用キノコ全般1)_台所の調理場", recipeLabel: "質素な肉料理(肉1+食用キノコ全般1)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "囲炉裏と調理鍋の仕事場(質素な肉料理(肉1+食用キノコ全般1))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "質素な肉料理(肉1+食用キノコ全般1)_囲炉裏と調理鍋の仕事場", recipeLabel: "質素な肉料理(肉1+食用キノコ全般1)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "酒場の調理場(質素な肉料理(肉1+豆全般5))": { displayName: "酒場の調理場", recipe: "質素な肉料理(肉1+豆全般5)_酒場の調理場", recipeLabel: "質素な肉料理(肉1+豆全般5)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "台所の調理場(質素な肉料理(肉1+豆全般5))": { displayName: "台所の調理場", recipe: "質素な肉料理(肉1+豆全般5)_台所の調理場", recipeLabel: "質素な肉料理(肉1+豆全般5)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "囲炉裏と調理鍋の仕事場(質素な肉料理(肉1+豆全般5))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "質素な肉料理(肉1+豆全般5)_囲炉裏と調理鍋の仕事場", recipeLabel: "質素な肉料理(肉1+豆全般5)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "酒場の調理場(きちんとした肉料理(肉1+卵1+豆全般6))": { displayName: "酒場の調理場", recipe: "きちんとした肉料理(肉1+卵1+豆全般6)_酒場の調理場", recipeLabel: "きちんとした肉料理(肉1+卵1+豆全般6)", facility_multiplier: 1, item_value: 52, tools: "no" },
        "台所の調理場(きちんとした肉料理(肉1+卵1+豆全般6))": { displayName: "台所の調理場", recipe: "きちんとした肉料理(肉1+卵1+豆全般6)_台所の調理場", recipeLabel: "きちんとした肉料理(肉1+卵1+豆全般6)", facility_multiplier: 1, item_value: 52, tools: "no" },
        "囲炉裏と調理鍋の仕事場(きちんとした肉料理(肉1+卵1+豆全般6))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "きちんとした肉料理(肉1+卵1+豆全般6)_囲炉裏と調理鍋の仕事場", recipeLabel: "きちんとした肉料理(肉1+卵1+豆全般6)", facility_multiplier: 1, item_value: 52, tools: "no" },
        "酒場の調理場(きちんとした肉料理(肉2+薬草全般2+穀物全般1))": { displayName: "酒場の調理場", recipe: "きちんとした肉料理(肉2+薬草全般2+穀物全般1)_酒場の調理場", recipeLabel: "きちんとした肉料理(肉2+薬草全般2+穀物全般1)", facility_multiplier: 1, item_value: 52, tools: "no" },
        "台所の調理場(きちんとした肉料理(肉2+薬草全般2+穀物全般1))": { displayName: "台所の調理場", recipe: "きちんとした肉料理(肉2+薬草全般2+穀物全般1)_台所の調理場", recipeLabel: "きちんとした肉料理(肉2+薬草全般2+穀物全般1)", facility_multiplier: 1, item_value: 52, tools: "no" },
        "囲炉裏と調理鍋の仕事場(きちんとした肉料理(肉2+薬草全般2+穀物全般1))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "きちんとした肉料理(肉2+薬草全般2+穀物全般1)_囲炉裏と調理鍋の仕事場", recipeLabel: "きちんとした肉料理(肉2+薬草全般2+穀物全般1)", facility_multiplier: 1, item_value: 52, tools: "no" },
        "酒場の調理場(きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6))": { displayName: "酒場の調理場", recipe: "きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6)_酒場の調理場", recipeLabel: "きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6)", facility_multiplier: 1, item_value: 52, tools: "no" },
        "台所の調理場(きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6))": { displayName: "台所の調理場", recipe: "きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6)_台所の調理場", recipeLabel: "きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6)", facility_multiplier: 1, item_value: 52, tools: "no" },
        "囲炉裏と調理鍋の仕事場(きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6)_囲炉裏と調理鍋の仕事場", recipeLabel: "きちんとした肉料理(肉1+薬草全般4+食用キノコ全般6)", facility_multiplier: 1, item_value: 52, tools: "no" },
        "酒場の調理場(豪華な肉料理(肉2+穀物全般4+豆全般4))": { displayName: "酒場の調理場", recipe: "豪華な肉料理(肉2+穀物全般4+豆全般4)_酒場の調理場", recipeLabel: "豪華な肉料理(肉2+穀物全般4+豆全般4)", facility_multiplier: 1, item_value: 72, tools: "no" },
        "酒場の調理場(豪華な肉料理(肉2+お米5+薬草全般3))": { displayName: "酒場の調理場", recipe: "豪華な肉料理(肉2+お米5+薬草全般3)_酒場の調理場", recipeLabel: "豪華な肉料理(肉2+お米5+薬草全般3)", facility_multiplier: 1, item_value: 72, tools: "no" },
        "酒場の調理場(豪華な肉料理(肉1+お米4+食用キノコ全般2))": { displayName: "酒場の調理場", recipe: "豪華な肉料理(肉1+お米4+食用キノコ全般2)_酒場の調理場", recipeLabel: "豪華な肉料理(肉1+お米4+食用キノコ全般2)", facility_multiplier: 1, item_value: 72, tools: "no" },
        "酒場の調理場(焼き鳥)": { displayName: "酒場の調理場", recipe: "焼き鳥_酒場の調理場", recipeLabel: "焼き鳥", facility_multiplier: 1, item_value: 61, tools: "no" },
        "酒場の調理場(質素な野菜料理(野菜全般5+豆全般3))": { displayName: "酒場の調理場", recipe: "質素な野菜料理(野菜全般5+豆全般3)_酒場の調理場", recipeLabel: "質素な野菜料理(野菜全般5+豆全般3)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "酒場の調理場(質素な野菜料理(野菜全般5+薬草全般3))": { displayName: "酒場の調理場", recipe: "質素な野菜料理(野菜全般5+薬草全般3)_酒場の調理場", recipeLabel: "質素な野菜料理(野菜全般5+薬草全般3)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "酒場の調理場(質素な野菜料理(野菜全般4+食用キノコ全般1))": { displayName: "酒場の調理場", recipe: "質素な野菜料理(野菜全般4+食用キノコ全般1)_酒場の調理場", recipeLabel: "質素な野菜料理(野菜全般4+食用キノコ全般1)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "酒場の調理場(きちんとした野菜料理(大豆10+麹2))": { displayName: "酒場の調理場", recipe: "きちんとした野菜料理(大豆10+麹2)_酒場の調理場", recipeLabel: "きちんとした野菜料理(大豆10+麹2)", facility_multiplier: 1, item_value: 50, tools: "no" },
        "酒場の調理場(きちんとした野菜料理(水1+穀物全般6+果実全般3))": { displayName: "酒場の調理場", recipe: "きちんとした野菜料理(水1+穀物全般6+果実全般3)_酒場の調理場", recipeLabel: "きちんとした野菜料理(水1+穀物全般6+果実全般3)", facility_multiplier: 1, item_value: 50, tools: "no" },
        "酒場の調理場(きちんとした野菜料理(水1+豆全般6+薬草全般3))": { displayName: "酒場の調理場", recipe: "きちんとした野菜料理(水1+豆全般6+薬草全般3)_酒場の調理場", recipeLabel: "きちんとした野菜料理(水1+豆全般6+薬草全般3)", facility_multiplier: 1, item_value: 50, tools: "no" },
        "酒場の調理場(豪華な野菜料理(穀物全般7+油1+水1+サトイモ8))": { displayName: "酒場の調理場", recipe: "豪華な野菜料理(穀物全般7+油1+水1+サトイモ8)_酒場の調理場", recipeLabel: "豪華な野菜料理(穀物全般7+油1+水1+サトイモ8)", facility_multiplier: 1, item_value: 71, tools: "no" },
        "酒場の調理場(豪華な野菜料理(お米12+しいたけ2+ネギ5+油1))": { displayName: "酒場の調理場", recipe: "豪華な野菜料理(お米12+しいたけ2+ネギ5+油1)_酒場の調理場", recipeLabel: "豪華な野菜料理(お米12+しいたけ2+ネギ5+油1)", facility_multiplier: 1, item_value: 71, tools: "no" },
        "酒場の調理場(豪華な野菜料理(小麦7+野菜全般8+わさび3+油1))": { displayName: "酒場の調理場", recipe: "豪華な野菜料理(小麦7+野菜全般8+わさび3+油1)_酒場の調理場", recipeLabel: "豪華な野菜料理(小麦7+野菜全般8+わさび3+油1)", facility_multiplier: 1, item_value: 71, tools: "no" },
        "酒場の調理場(豆腐)": { displayName: "酒場の調理場", recipe: "豆腐_酒場の調理場", recipeLabel: "豆腐", facility_multiplier: 1, item_value: 28, tools: "no" },
        "酒場の調理場(田楽)": { displayName: "酒場の調理場", recipe: "田楽_酒場の調理場", recipeLabel: "田楽", facility_multiplier: 1, item_value: 60, tools: "no" },
        "台所の調理場(田楽)": { displayName: "台所の調理場", recipe: "田楽_台所の調理場", recipeLabel: "田楽", facility_multiplier: 1, item_value: 60, tools: "no" },
        "台所の調理場(焼き鳥)": { displayName: "台所の調理場", recipe: "焼き鳥_台所の調理場", recipeLabel: "焼き鳥", facility_multiplier: 1, item_value: 61, tools: "no" },
        "台所の調理場(味噌)": { displayName: "台所の調理場", recipe: "味噌_台所の調理場", recipeLabel: "味噌", facility_multiplier: 1, item_value: 29, tools: "no" },
        "台所の調理場(豆腐)": { displayName: "台所の調理場", recipe: "豆腐_台所の調理場", recipeLabel: "豆腐", facility_multiplier: 1, item_value: 28, tools: "no" },
        "台所の調理場(質素な野菜料理(野菜全般5+豆全般3))": { displayName: "台所の調理場", recipe: "質素な野菜料理(野菜全般5+豆全般3)_台所の調理場", recipeLabel: "質素な野菜料理(野菜全般5+豆全般3)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "囲炉裏と調理鍋の仕事場(質素な野菜料理(野菜全般5+豆全般3))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "質素な野菜料理(野菜全般5+豆全般3)_囲炉裏と調理鍋の仕事場", recipeLabel: "質素な野菜料理(野菜全般5+豆全般3)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "囲炉裏の仕事場(質素な野菜料理(野菜全般5+豆全般3))": { displayName: "囲炉裏の仕事場", recipe: "質素な野菜料理(野菜全般5+豆全般3)_囲炉裏の仕事場", recipeLabel: "質素な野菜料理(野菜全般5+豆全般3)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "台所の調理場(質素な野菜料理(野菜全般5+薬草全般3))": { displayName: "台所の調理場", recipe: "質素な野菜料理(野菜全般5+薬草全般3)_台所の調理場", recipeLabel: "質素な野菜料理(野菜全般5+薬草全般3)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "囲炉裏と調理鍋の仕事場(質素な野菜料理(野菜全般5+薬草全般3))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "質素な野菜料理(野菜全般5+薬草全般3)_囲炉裏と調理鍋の仕事場", recipeLabel: "質素な野菜料理(野菜全般5+薬草全般3)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "囲炉裏の仕事場(質素な野菜料理(野菜全般5+薬草全般3))": { displayName: "囲炉裏の仕事場", recipe: "質素な野菜料理(野菜全般5+薬草全般3)_囲炉裏の仕事場", recipeLabel: "質素な野菜料理(野菜全般5+薬草全般3)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "台所の調理場(質素な野菜料理(野菜全般4+食用キノコ全般1))": { displayName: "台所の調理場", recipe: "質素な野菜料理(野菜全般4+食用キノコ全般1)_台所の調理場", recipeLabel: "質素な野菜料理(野菜全般4+食用キノコ全般1)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "囲炉裏と調理鍋の仕事場(質素な野菜料理(野菜全般4+食用キノコ全般1))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "質素な野菜料理(野菜全般4+食用キノコ全般1)_囲炉裏と調理鍋の仕事場", recipeLabel: "質素な野菜料理(野菜全般4+食用キノコ全般1)", facility_multiplier: 1, item_value: 25, tools: "no" },
        "台所の調理場(きちんとした野菜料理(大豆10+麹2))": { displayName: "台所の調理場", recipe: "きちんとした野菜料理(大豆10+麹2)_台所の調理場", recipeLabel: "きちんとした野菜料理(大豆10+麹2)", facility_multiplier: 1, item_value: 50, tools: "no" },
        "囲炉裏と調理鍋の仕事場(きちんとした野菜料理(大豆10+麹2))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "きちんとした野菜料理(大豆10+麹2)_囲炉裏と調理鍋の仕事場", recipeLabel: "きちんとした野菜料理(大豆10+麹2)", facility_multiplier: 1, item_value: 50, tools: "no" },
        "台所の調理場(きちんとした野菜料理(水1+穀物全般6+果実全般3))": { displayName: "台所の調理場", recipe: "きちんとした野菜料理(水1+穀物全般6+果実全般3)_台所の調理場", recipeLabel: "きちんとした野菜料理(水1+穀物全般6+果実全般3)", facility_multiplier: 1, item_value: 50, tools: "no" },
        "囲炉裏と調理鍋の仕事場(きちんとした野菜料理(水1+穀物全般6+果実全般3))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "きちんとした野菜料理(水1+穀物全般6+果実全般3)_囲炉裏と調理鍋の仕事場", recipeLabel: "きちんとした野菜料理(水1+穀物全般6+果実全般3)", facility_multiplier: 1, item_value: 50, tools: "no" },
        "台所の調理場(きちんとした野菜料理(水1+豆全般6+薬草全般3))": { displayName: "台所の調理場", recipe: "きちんとした野菜料理(水1+豆全般6+薬草全般3)_台所の調理場", recipeLabel: "きちんとした野菜料理(水1+豆全般6+薬草全般3)", facility_multiplier: 1, item_value: 50, tools: "no" },
        "囲炉裏と調理鍋の仕事場(きちんとした野菜料理(水1+豆全般6+薬草全般3))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "きちんとした野菜料理(水1+豆全般6+薬草全般3)_囲炉裏と調理鍋の仕事場", recipeLabel: "きちんとした野菜料理(水1+豆全般6+薬草全般3)", facility_multiplier: 1, item_value: 50, tools: "no" },
        "囲炉裏と調理鍋の仕事場(団子)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "団子_囲炉裏と調理鍋の仕事場", recipeLabel: "団子", facility_multiplier: 1, item_value: 32, tools: "no" },
        "囲炉裏の仕事場(団子)": { displayName: "囲炉裏の仕事場", recipe: "団子_囲炉裏の仕事場", recipeLabel: "団子", facility_multiplier: 1, item_value: 32, tools: "no" },
        "酒場の調理場(調理した肉)": { displayName: "酒場の調理場", recipe: "調理した肉_酒場の調理場", recipeLabel: "調理した肉", facility_multiplier: 1, item_value: 11, tools: "no" },
        "台所の調理場(調理した肉)": { displayName: "台所の調理場", recipe: "調理した肉_台所の調理場", recipeLabel: "調理した肉", facility_multiplier: 1, item_value: 11, tools: "no" },
        "囲炉裏と調理鍋の仕事場(調理した肉)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "調理した肉_囲炉裏と調理鍋の仕事場", recipeLabel: "調理した肉", facility_multiplier: 1, item_value: 11, tools: "no" },
        "囲炉裏の仕事場(調理した肉)": { displayName: "囲炉裏の仕事場", recipe: "調理した肉_囲炉裏の仕事場", recipeLabel: "調理した肉", facility_multiplier: 1, item_value: 11, tools: "no" },
        "採集者の仕事場(柚子の果実)": { displayName: "採集者の仕事場", recipe: "柚子の果実_採集者の仕事場", recipeLabel: "柚子の果実", facility_multiplier: 1, item_value: 4, tools: "no" },
        "採集者の仕事場(ゴボウ)": { displayName: "採集者の仕事場", recipe: "ゴボウ_採集者の仕事場", recipeLabel: "ゴボウ", facility_multiplier: 1, item_value: 2, tools: "no" },
        "採集者の仕事場(えのき)": { displayName: "採集者の仕事場", recipe: "えのき_採集者の仕事場", recipeLabel: "えのき", facility_multiplier: 1, item_value: 4, tools: "no" },
        "採集者の仕事場(舞茸)": { displayName: "採集者の仕事場", recipe: "舞茸_採集者の仕事場", recipeLabel: "舞茸", facility_multiplier: 1, item_value: 4, tools: "no" },
        "採集者の仕事場(松茸)": { displayName: "採集者の仕事場", recipe: "松茸_採集者の仕事場", recipeLabel: "松茸", facility_multiplier: 1, item_value: 4, tools: "no" },
        "採集者の仕事場(しいたけ)": { displayName: "採集者の仕事場", recipe: "しいたけ_採集者の仕事場", recipeLabel: "しいたけ", facility_multiplier: 1, item_value: 4, tools: "no" },
        "採集者の仕事場(ヒョウタンノキの実)": { displayName: "採集者の仕事場", recipe: "ヒョウタンノキの実_採集者の仕事場", recipeLabel: "ヒョウタンノキの実", facility_multiplier: 1, item_value: 4, tools: "no" },
        "採集者の仕事場(わさび)": { displayName: "採集者の仕事場", recipe: "わさび_採集者の仕事場", recipeLabel: "わさび", facility_multiplier: 1, item_value: 1, tools: "no" },
        "採集者の仕事場(ニンニク)": { displayName: "採集者の仕事場", recipe: "ニンニク_採集者の仕事場", recipeLabel: "ニンニク", facility_multiplier: 1, item_value: 1, tools: "no" },
        "採集者の仕事場(三つ葉)": { displayName: "採集者の仕事場", recipe: "三つ葉_採集者の仕事場", recipeLabel: "三つ葉", facility_multiplier: 1, item_value: 2, tools: "no" },
        "採集者の仕事場(木苺)": { displayName: "採集者の仕事場", recipe: "木苺_採集者の仕事場", recipeLabel: "木苺", facility_multiplier: 1, item_value: 2, tools: "no" },
        "採集者の仕事場(コケモモ)": { displayName: "採集者の仕事場", recipe: "コケモモ_採集者の仕事場", recipeLabel: "コケモモ", facility_multiplier: 1, item_value: 2, tools: "no" },
        "採集者の仕事場(プラム)": { displayName: "採集者の仕事場", recipe: "プラム_採集者の仕事場", recipeLabel: "プラム", facility_multiplier: 1, item_value: 3, tools: "no" },
        "調薬台(兵糧丸)": { displayName: "調薬台", recipe: "兵糧丸_調薬台", recipeLabel: "兵糧丸", facility_multiplier: 3, item_value: 35, tools: "no" },
        "小さな蜜蜂の巣箱": { recipe: "蜂蜜_小さな蜜蜂の巣箱", recipeLabel: "蜂蜜", facility_multiplier: 1, item_value: 4, tools: "no" },
        "大きな蜜蜂の巣箱": { recipe: "蜂蜜_大きな蜜蜂の巣箱", recipeLabel: "蜂蜜", facility_multiplier: 1, item_value: 4, tools: "no" }
      }
    },
    "安全性": {
      facilities: {
        "地侍のやぐら(近接)": { displayName: "地侍のやぐら", recipe: "衛兵_近接武器", recipeLabel: "近接武器", facility_multiplier: 50, item_value: 1, tools: "近接武器" },
        "地侍のやぐら(遠距離)": { displayName: "地侍のやぐら", recipe: "衛兵_遠距離武器", recipeLabel: "遠距離武器", facility_multiplier: 50, item_value: 1, tools: "遠距離武器" },
        "小さなやぐら(近接)": { displayName: "小さなやぐら", recipe: "衛兵_近接武器", recipeLabel: "近接武器", facility_multiplier: 30, item_value: 1, tools: "近接武器" },
        "小さなやぐら(遠距離)": { displayName: "小さなやぐら", recipe: "衛兵_遠距離武器", recipeLabel: "遠距離武器", facility_multiplier: 30, item_value: 1, tools: "遠距離武器" },
        "猟師の小さなやぐら(近接)": { displayName: "猟師の小さなやぐら", recipe: "衛兵_近接武器", recipeLabel: "近接武器", facility_multiplier: 40, item_value: 1, tools: "近接武器" },
        "猟師の小さなやぐら(遠距離)": { displayName: "猟師の小さなやぐら", recipe: "衛兵_遠距離武器", recipeLabel: "遠距離武器", facility_multiplier: 40, item_value: 1, tools: "遠距離武器" },
        "特殊建造物「物見やぐら」": { recipe: "物見やぐら_専用", recipeLabel: "衛兵", facility_multiplier: 1, item_value: 1, tools: "武器全般" },
        "特殊建造物「灯台」": { recipe: "灯籠夫_灯台", recipeLabel: "灯籠夫", facility_multiplier: 20, item_value: 1, tools: "no" }
      }
    },
    "暖かさ": {
      facilities: {
        "酒場の調理場(油(魚))": { displayName: "酒場の調理場", recipe: "油(魚)_酒場の調理場", recipeLabel: "油(魚)", facility_multiplier: 1, item_value: 45, tools: "no" },
        "台所の調理場(油(魚))": { displayName: "台所の調理場", recipe: "油(魚)_台所の調理場", recipeLabel: "油(魚)", facility_multiplier: 1, item_value: 45, tools: "no" },
        "囲炉裏と調理鍋の仕事場(油(魚))": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "油(魚)_囲炉裏と調理鍋の仕事場", recipeLabel: "油(魚)", facility_multiplier: 1, item_value: 45, tools: "no" },
        "搾油(油)": { displayName: "搾油", recipe: "油_搾油", recipeLabel: "油", facility_multiplier: 1, item_value: 45, tools: "no" },
        "採集者の仕事場(枝)": { displayName: "採集者の仕事場", recipe: "枝_採集者の仕事場", recipeLabel: "枝", facility_multiplier: 1, item_value: 1, tools: "no" },
        "採集者の仕事場(樹皮)": { displayName: "採集者の仕事場", recipe: "樹皮_採集者の仕事場", recipeLabel: "樹皮", facility_multiplier: 1, item_value: 1, tools: "no" },
        "採集者の仕事場(梶の樹皮)": { displayName: "採集者の仕事場", recipe: "梶の樹皮_採集者の仕事場", recipeLabel: "梶の樹皮", facility_multiplier: 1, item_value: 1, tools: "no" },
        "炭窯": { recipe: "木炭_炭窯", recipeLabel: "木炭", facility_multiplier: 2, item_value: 12, tools: "no" },
        "大工作業台(薪)": { displayName: "大工作業台", recipe: "薪_大工作業台", recipeLabel: "薪", facility_multiplier: 8, item_value: 5, tools: "斧全般" },
        "仕立て台(蓑)": { displayName: "仕立て台", recipe: "蓑_仕立て台", recipeLabel: "蓑", facility_multiplier: 1, item_value: 140, tools: "no" }
      }
    },
    "信仰": {
      facilities: {
        "僧院の鐘楼": { recipe: "神主_鐘楼", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "僧院の手水舎": { recipe: "神主_手水舎", recipeLabel: "神主", facility_multiplier: 6, item_value: 1, tools: "no" },
        "小さな天照神社": { recipe: "神主_小社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "天照神社": { recipe: "神主_中社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "大きな天照神社": { recipe: "神主_大社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "小さな恵比寿神社": { recipe: "神主_小社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "恵比寿神社": { recipe: "神主_中社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "大きな恵比寿神社": { recipe: "神主_大社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "小さな稲荷神社": { recipe: "神主_小社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "稲荷神社": { recipe: "神主_中社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "大きな稲荷神社": { recipe: "神主_大社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "小さな地蔵神社": { recipe: "神主_小社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "地蔵神社": { recipe: "神主_中社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "大きな地蔵神社": { recipe: "神主_大社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "小さな観音神社": { recipe: "神主_小社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "観音神社": { recipe: "神主_中社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "大きな観音神社": { recipe: "神主_大社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "小さな龍神社": { recipe: "神主_小社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "龍神社": { recipe: "神主_中社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "大きな龍神社": { recipe: "神主_大社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "小さな天神社": { recipe: "神主_小社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "天神社": { recipe: "神主_中社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "大きな天神社": { recipe: "神主_大社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "小さな八幡神社": { recipe: "神主_小社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "八幡神社": { recipe: "神主_中社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "大きな八幡神社": { recipe: "神主_大社", recipeLabel: "神主", facility_multiplier: 50, item_value: 1, tools: "no" },
        "金敷(小さな銅鑼)": { displayName: "金敷", recipe: "小さな銅鑼_金敷", recipeLabel: "小さな銅鑼", facility_multiplier: 2, item_value: 95, tools: "槌全般" },
        "金敷(鈴)": { displayName: "金敷", recipe: "鈴_金敷", recipeLabel: "鈴", facility_multiplier: 1, item_value: 425, tools: "槌全般" },
        "金敷(儀式の鐘)": { displayName: "金敷", recipe: "儀式の鐘_金敷", recipeLabel: "儀式の鐘", facility_multiplier: 1, item_value: 80, tools: "槌全般" },
        "金敷(青銅の灯篭)": { displayName: "金敷", recipe: "青銅の灯篭_金敷", recipeLabel: "青銅の灯篭", facility_multiplier: 1, item_value: 350, tools: "槌全般" },
        "石工所(天照大御神の像)": { displayName: "石工所", recipe: "天照大御神の像_石工所", recipeLabel: "天照大御神の像", facility_multiplier: 1, item_value: 110, tools: "彫刻刀" },
        "石工所(稲荷像)": { displayName: "石工所", recipe: "稲荷像_石工所", recipeLabel: "稲荷像", facility_multiplier: 1, item_value: 110, tools: "彫刻刀" },
        "石工所(地蔵像)": { displayName: "石工所", recipe: "地蔵像_石工所", recipeLabel: "地蔵像", facility_multiplier: 1, item_value: 110, tools: "彫刻刀" },
        "石工所(観音像)": { displayName: "石工所", recipe: "観音像_石工所", recipeLabel: "観音像", facility_multiplier: 1, item_value: 110, tools: "彫刻刀" },
        "石工所(龍神像)": { displayName: "石工所", recipe: "龍神像_石工所", recipeLabel: "龍神像", facility_multiplier: 1, item_value: 110, tools: "彫刻刀" },
        "石工所(恵比寿像)": { displayName: "石工所", recipe: "恵比寿像_石工所", recipeLabel: "恵比寿像", facility_multiplier: 1, item_value: 110, tools: "彫刻刀" },
        "石工所(天神像)": { displayName: "石工所", recipe: "天神像_石工所", recipeLabel: "天神像", facility_multiplier: 1, item_value: 110, tools: "彫刻刀" },
        "石工所(八幡像)": { displayName: "石工所", recipe: "八幡像_石工所", recipeLabel: "八幡像", facility_multiplier: 1, item_value: 110, tools: "彫刻刀" },
        "木工作業台(木製の数珠)": { displayName: "木工作業台", recipe: "木製の数珠_木工作業台", recipeLabel: "木製の数珠", facility_multiplier: 1, item_value: 8, tools: "no" },
        "木工作業台(真珠の数珠)": { displayName: "木工作業台", recipe: "真珠の数珠_木工作業台", recipeLabel: "真珠の数珠", facility_multiplier: 1, item_value: 500, tools: "no" },
        "木工作業台(貝殻の数珠)": { displayName: "木工作業台", recipe: "貝殻の数珠_木工作業台", recipeLabel: "貝殻の数珠", facility_multiplier: 1, item_value: 40, tools: "no" },
        "木工作業台(仏舎利塔のミニチュア)": { displayName: "木工作業台", recipe: "仏舎利塔のミニチュア_木工作業台", recipeLabel: "仏舎利塔のミニチュア", facility_multiplier: 1, item_value: 60, tools: "彫刻刀" },
        "木工作業台(玉串)": { displayName: "木工作業台", recipe: "玉串_木工作業台", recipeLabel: "玉串", facility_multiplier: 1, item_value: 10, tools: "no" },
        "木工作業台(笛)": { displayName: "木工作業台", recipe: "笛_木工作業台", recipeLabel: "笛", facility_multiplier: 1, item_value: 60, tools: "彫刻刀" },
        "木工作業台(小さな御幣)": { displayName: "木工作業台", recipe: "小さな御幣_木工作業台", recipeLabel: "小さな御幣", facility_multiplier: 3, item_value: 12, tools: "no" },
        "仕立て台(僧の服)": { displayName: "仕立て台", recipe: "僧の服_仕立て台", recipeLabel: "僧の服", facility_multiplier: 1, item_value: 260, tools: "小刀全般" },
        "仕立て台(僧の被り物)": { displayName: "仕立て台", recipe: "僧の被り物_仕立て台", recipeLabel: "僧の被り物", facility_multiplier: 1, item_value: 300, tools: "no" },
        "仕立て台(天蓋)": { displayName: "仕立て台", recipe: "天蓋_仕立て台", recipeLabel: "天蓋", facility_multiplier: 1, item_value: 325, tools: "no" },
        "仕立て台(神主の装束)": { displayName: "仕立て台", recipe: "神主の装束_仕立て台", recipeLabel: "神主の装束", facility_multiplier: 1, item_value: 375, tools: "小刀全般" },
        "仕立て台(冠)": { displayName: "仕立て台", recipe: "冠_仕立て台", recipeLabel: "冠", facility_multiplier: 1, item_value: 400, tools: "小刀全般" },
        "仕立て台(僧兵の服)": { displayName: "仕立て台", recipe: "僧兵の服_仕立て台", recipeLabel: "僧兵の服", facility_multiplier: 1, item_value: 350, tools: "小刀全般" }
      }
    },
    "健康": {
      facilities: {
        "僧院の手水舎": { recipe: "神主_手水舎", recipeLabel: "神主", facility_multiplier: 6, item_value: 1, tools: "no" },
        "酒場(水x2)": { displayName: "酒場", recipe: "酒場の主人(水x2)", recipeLabel: "酒場の主人(水x2)", facility_multiplier: 6, item_value: 1, tools: "no" },
        "酒場(水x1+アルコールを含まない飲料全般x1)": { displayName: "酒場", recipe: "酒場の主人(水x1+アルコールを含まない飲料全般x1)", recipeLabel: "酒場の主人(水x1+アルコールを含まない飲料全般x1)", facility_multiplier: 6, item_value: 1, tools: "no" },
        "酒場(水x1+アルコール飲料全般x1)": { displayName: "酒場", recipe: "酒場の主人(水x1+アルコール飲料全般x1)", recipeLabel: "酒場の主人(水x1+アルコール飲料全般x1)", facility_multiplier: 4, item_value: 1, tools: "no" },
        "採集者の仕事場(菊の花)": { displayName: "採集者の仕事場", recipe: "菊の花_採集者の仕事場", recipeLabel: "菊の花", facility_multiplier: 1, item_value: 1, tools: "no" },
        "調薬台(治癒の飲料)": { displayName: "調薬台", recipe: "治癒の飲料_調薬台", recipeLabel: "治癒の飲料", facility_multiplier: 1, item_value: 15, tools: "no" },
        "調薬台(治癒の包帯)": { displayName: "調薬台", recipe: "治癒の包帯_調薬台", recipeLabel: "治癒の包帯", facility_multiplier: 1, item_value: 50, tools: "no" },
        "調薬台(治癒の軟膏)": { displayName: "調薬台", recipe: "治癒の軟膏_調薬台", recipeLabel: "治癒の軟膏", facility_multiplier: 1, item_value: 90, tools: "no" },
        "調薬台(火傷軟膏)": { displayName: "調薬台", recipe: "火傷軟膏_調薬台", recipeLabel: "火傷軟膏", facility_multiplier: 1, item_value: 30, tools: "no" },
        "調薬台(温かい飲み物)": { displayName: "調薬台", recipe: "温かい飲み物_調薬台", recipeLabel: "温かい飲み物", facility_multiplier: 1, item_value: 12, tools: "no" },
        "調薬台(風邪薬)": { displayName: "調薬台", recipe: "風邪薬_調薬台", recipeLabel: "風邪薬", facility_multiplier: 1, item_value: 25, tools: "no" },
        "調薬台(栄養剤)": { displayName: "調薬台", recipe: "栄養剤_調薬台", recipeLabel: "栄養剤", facility_multiplier: 1, item_value: 43, tools: "no" },
        "調薬台(蚊よけ)": { displayName: "調薬台", recipe: "蚊よけ_調薬台", recipeLabel: "蚊よけ", facility_multiplier: 1, item_value: 60, tools: "no" },
        "調薬台(冷たい飲み物)": { displayName: "調薬台", recipe: "冷たい飲み物_調薬台", recipeLabel: "冷たい飲み物", facility_multiplier: 1, item_value: 40, tools: "no" },
        "調薬台(痛み止め)": { displayName: "調薬台", recipe: "痛み止め_調薬台", recipeLabel: "痛み止め", facility_multiplier: 1, item_value: 125, tools: "no" },
        "調薬台(対毒調合薬)": { displayName: "調薬台", recipe: "対毒調合薬_調薬台", recipeLabel: "対毒調合薬", facility_multiplier: 1, item_value: 175, tools: "no" },
        "調薬台(解毒薬)": { displayName: "調薬台", recipe: "解毒薬_調薬台", recipeLabel: "解毒薬", facility_multiplier: 1, item_value: 235, tools: "no" },
        "調薬台(マラリア治療薬)": { displayName: "調薬台", recipe: "マラリア治療薬_調薬台", recipeLabel: "マラリア治療薬", facility_multiplier: 1, item_value: 260, tools: "no" },
        "調薬台(果実の抽出液)": { displayName: "調薬台", recipe: "果実の抽出液_調薬台", recipeLabel: "果実の抽出液", facility_multiplier: 1, item_value: 30, tools: "no" },
        "調薬台(プラムの抽出液)": { displayName: "調薬台", recipe: "プラムの抽出液_調薬台", recipeLabel: "プラムの抽出液", facility_multiplier: 1, item_value: 50, tools: "no" },
        "調薬台(柚子の抽出液)": { displayName: "調薬台", recipe: "柚子の抽出液_調薬台", recipeLabel: "柚子の抽出液", facility_multiplier: 1, item_value: 50, tools: "no" }
      }
    },
    "飲み物": {
      facilities: {
        "シンプルな井戸": { recipe: "水_シンプル井戸", recipeLabel: "水", facility_multiplier: 1, item_value: 4, tools: "桶" },
        "上級井戸": { recipe: "水_上級井戸", recipeLabel: "水", facility_multiplier: 1, item_value: 4, tools: "桶" },
        "大きな井戸": { recipe: "水_大井戸", recipeLabel: "水", facility_multiplier: 1, item_value: 4, tools: "桶" },
        "茶室": { recipe: "茶室_茶会", recipeLabel: "茶会", facility_multiplier: 1, item_value: 10, tools: "no" },
        "酒場の調理場(茶)": { displayName: "酒場の調理場", recipe: "茶(酒場の調理場版)_酒場の調理場", recipeLabel: "茶", facility_multiplier: 2, item_value: 10, tools: "no" },
        "台所の調理場(茶)": { displayName: "台所の調理場", recipe: "茶(酒場の調理場版)_台所の調理場", recipeLabel: "茶", facility_multiplier: 2, item_value: 10, tools: "no" },
        "囲炉裏と調理鍋の仕事場(茶)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "茶(酒場の調理場版)_囲炉裏と調理鍋の仕事場", recipeLabel: "茶", facility_multiplier: 2, item_value: 10, tools: "no" },
        "酒場の調理場(甘酒)": { displayName: "酒場の調理場", recipe: "甘酒_酒場の調理場", recipeLabel: "甘酒", facility_multiplier: 2, item_value: 8, tools: "no" },
        "台所の調理場(甘酒)": { displayName: "台所の調理場", recipe: "甘酒_台所の調理場", recipeLabel: "甘酒", facility_multiplier: 2, item_value: 8, tools: "no" },
        "囲炉裏と調理鍋の仕事場(甘酒)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "甘酒_囲炉裏と調理鍋の仕事場", recipeLabel: "甘酒", facility_multiplier: 2, item_value: 8, tools: "no" },
        "囲炉裏の仕事場(甘酒)": { displayName: "囲炉裏の仕事場", recipe: "甘酒_囲炉裏の仕事場", recipeLabel: "甘酒", facility_multiplier: 2, item_value: 8, tools: "no" },
        "酒場の調理場(どぶろく)": { displayName: "酒場の調理場", recipe: "どぶろく_酒場の調理場", recipeLabel: "どぶろく", facility_multiplier: 4, item_value: 18, tools: "no" },
        "台所の調理場(どぶろく)": { displayName: "台所の調理場", recipe: "どぶろく_台所の調理場", recipeLabel: "どぶろく", facility_multiplier: 4, item_value: 18, tools: "no" },
        "圧力ろ過器(日本酒)": { displayName: "圧力ろ過器", recipe: "日本酒_圧力ろ過器", recipeLabel: "日本酒", facility_multiplier: 4, item_value: 36, tools: "no" },
        "焼酎蒸留所(焼酎)": { displayName: "焼酎蒸留所", recipe: "焼酎_焼酎蒸留所", recipeLabel: "焼酎", facility_multiplier: 6, item_value: 60, tools: "no" },
        "仕立て台(ヒョウタンノキの水容器)": { displayName: "仕立て台", recipe: "ヒョウタンノキの水容器_仕立て台", recipeLabel: "ヒョウタンノキの水容器", facility_multiplier: 1, item_value: 150, tools: "小刀全般" },
        "囲炉裏と調理鍋の仕事場(どぶろく)": { displayName: "囲炉裏と調理鍋の仕事場", recipe: "どぶろく_囲炉裏と調理鍋の仕事場", recipeLabel: "どぶろく", facility_multiplier: 4, item_value: 18, tools: "no" },
        "囲炉裏の仕事場(どぶろく)": { displayName: "囲炉裏の仕事場", recipe: "どぶろく_囲炉裏の仕事場", recipeLabel: "どぶろく", facility_multiplier: 4, item_value: 18, tools: "no" }
      }
    },
    "贅沢": {
      facilities: {
        "茶室": { recipe: "茶室_茶会", recipeLabel: "茶会", facility_multiplier: 5, item_value: 1, tools: "no" },
        "仕立て台(深靴)": { displayName: "仕立て台", recipe: "深靴_仕立て台", recipeLabel: "深靴", facility_multiplier: 1, item_value: 255, tools: "小刀全般" },
        "仕立て台(浪人笠)": { displayName: "仕立て台", recipe: "浪人笠_仕立て台", recipeLabel: "浪人笠", facility_multiplier: 1, item_value: 325, tools: "no" },
        "仕立て台(網代笠)": { displayName: "仕立て台", recipe: "網代笠_仕立て台", recipeLabel: "網代笠(あじろがさ)", facility_multiplier: 1, item_value: 180, tools: "no" },
        "なめし槽(革)": { recipe: "革_なめし槽", recipeLabel: "革", facility_multiplier: 1, item_value: 65, tools: "攪拌道具" },
        "仕立て台(村人の服)": { displayName: "仕立て台", recipe: "村人の服_仕立て台", recipeLabel: "村人の服", facility_multiplier: 1, item_value: 130, tools: "小刀全般" },
        "仕立て台(貴族の服)": { displayName: "仕立て台", recipe: "貴族の服_仕立て台", recipeLabel: "貴族の服", facility_multiplier: 1, item_value: 500, tools: "小刀全般" },
        "仕立て台(盗賊の服)": { displayName: "仕立て台", recipe: "盗賊の服_仕立て台", recipeLabel: "盗賊の服", facility_multiplier: 1, item_value: 95, tools: "小刀全般" },
        "仕立て台(靴下)": { displayName: "仕立て台", recipe: "靴下_仕立て台", recipeLabel: "靴下", facility_multiplier: 1, item_value: 50, tools: "小刀全般" },
        "仕立て台(般若の面)": { displayName: "仕立て台", recipe: "般若の面_仕立て台", recipeLabel: "般若の面", facility_multiplier: 1, item_value: 150, tools: "釿全般" },
        "仕立て台(田下駄)": { displayName: "仕立て台", recipe: "田下駄_仕立て台", recipeLabel: "田下駄", facility_multiplier: 1, item_value: 250, tools: "釿全般" },
        "仕立て台(草鞋)": { displayName: "仕立て台", recipe: "草鞋_仕立て台", recipeLabel: "草鞋(わらじ)", facility_multiplier: 1, item_value: 20, tools: "小刀全般" },
        "仕立て台(農民の服)": { displayName: "仕立て台", recipe: "農民の服_仕立て台", recipeLabel: "農民の服", facility_multiplier: 1, item_value: 45, tools: "小刀全般" },
        "仕立て台(天狗の面)": { displayName: "仕立て台", recipe: "天狗の面_仕立て台", recipeLabel: "天狗の面", facility_multiplier: 1, item_value: 100, tools: "釿全般" },
        "仕立て台(藁帽子)": { displayName: "仕立て台", recipe: "藁帽子_仕立て台", recipeLabel: "藁帽子", facility_multiplier: 1, item_value: 90, tools: "no" },
        "仕立て台(下駄)": { displayName: "仕立て台", recipe: "下駄_仕立て台", recipeLabel: "下駄", facility_multiplier: 1, item_value: 60, tools: "no" },
        "仕立て台(一本下駄)": { displayName: "仕立て台", recipe: "一本下駄_仕立て台", recipeLabel: "一本下駄", facility_multiplier: 1, item_value: 200, tools: "no" },
        "仕立て台(盗賊の被り物)": { displayName: "仕立て台", recipe: "盗賊の被り物_仕立て台", recipeLabel: "盗賊の被り物", facility_multiplier: 1, item_value: 46, tools: "小刀全般" },
        "仕立て台(狐の面)": { displayName: "仕立て台", recipe: "狐の面_仕立て台", recipeLabel: "狐の面", facility_multiplier: 1, item_value: 80, tools: "釿全般" },
        "仕立て台(翁の面)": { displayName: "仕立て台", recipe: "翁の面_仕立て台", recipeLabel: "翁の面", facility_multiplier: 1, item_value: 60, tools: "釿全般" },
        "仕立て台(素朴な印籠)": { displayName: "仕立て台", recipe: "素朴な印籠_仕立て台", recipeLabel: "素朴な印籠", facility_multiplier: 1, item_value: 48, tools: "小刀全般" },
        "仕立て台(匠の印籠)": { displayName: "仕立て台", recipe: "匠の印籠_仕立て台", recipeLabel: "匠の印籠", facility_multiplier: 1, item_value: 300, tools: "小刀全般" },
        "仕立て台(飾りつきの印籠)": { displayName: "仕立て台", recipe: "飾りつきの印籠_仕立て台", recipeLabel: "飾りつきの印籠", facility_multiplier: 1, item_value: 115, tools: "小刀全般" },
        "仕立て台(足袋付きの草鞋)": { displayName: "仕立て台", recipe: "足袋付きの草鞋_仕立て台", recipeLabel: "足袋付きの草鞋", facility_multiplier: 1, item_value: 40, tools: "小刀全般" },
        "仕立て台(毛沓)": { displayName: "仕立て台", recipe: "毛沓_仕立て台", recipeLabel: "毛沓", facility_multiplier: 1, item_value: 260, tools: "小刀全般" },
        "仕立て台(浅沓)": { displayName: "仕立て台", recipe: "浅沓_仕立て台", recipeLabel: "浅沓", facility_multiplier: 1, item_value: 275, tools: "小刀全般" },
        "仕立て台(藁の輪)": { displayName: "仕立て台", recipe: "藁の輪_仕立て台", recipeLabel: "藁の輪", facility_multiplier: 1, item_value: 38, tools: "小刀全般" },
        "仕立て台(裕福な商人の服)": { displayName: "仕立て台", recipe: "裕福な商人の服_仕立て台", recipeLabel: "裕福な商人の服", facility_multiplier: 1, item_value: 315, tools: "小刀全般" },
        "仕立て台(軽量の侍の服)": { displayName: "仕立て台", recipe: "軽量の侍の服_仕立て台", recipeLabel: "軽量の侍の服", facility_multiplier: 1, item_value: 550, tools: "小刀全般" },
        "仕立て台(商人の服・リネンx8)": { displayName: "仕立て台", recipe: "商人の服(リネンx8)_仕立て台", recipeLabel: "商人の服(リネンx8)", facility_multiplier: 1, item_value: 55, tools: "小刀全般" },
        "仕立て台(商人の服・リネンx20)": { displayName: "仕立て台", recipe: "商人の服(リネンx20)_仕立て台", recipeLabel: "商人の服(リネンx20)", facility_multiplier: 1, item_value: 250, tools: "小刀全般" },
        "仕立て台(養蜂家の枝細工の面)": { displayName: "仕立て台", recipe: "養蜂家の枝細工の面_仕立て台", recipeLabel: "養蜂家の枝細工の面", facility_multiplier: 1, item_value: 100, tools: "小刀全般" },
        "仕立て台(養蜂家の被り物)": { displayName: "仕立て台", recipe: "養蜂家の被り物_仕立て台", recipeLabel: "養蜂家の被り物", facility_multiplier: 1, item_value: 150, tools: "小刀全般" },
        "仕立て台(養蜂家の服)": { displayName: "仕立て台", recipe: "養蜂家の服_仕立て台", recipeLabel: "養蜂家の服", facility_multiplier: 1, item_value: 260, tools: "小刀全般" },
        "仕立て台(烏天狗の面)": { displayName: "仕立て台", recipe: "烏天狗の面_仕立て台", recipeLabel: "烏天狗の面", facility_multiplier: 1, item_value: 150, tools: "釿全般" },
        "仕立て台(化け猫の面)": { displayName: "仕立て台", recipe: "化け猫の面_仕立て台", recipeLabel: "化け猫の面", facility_multiplier: 1, item_value: 125, tools: "釿全般" },
        "仕立て台(浪人の服)": { displayName: "仕立て台", recipe: "浪人の服_仕立て台", recipeLabel: "浪人の服", facility_multiplier: 1, item_value: 245, tools: "小刀全般" },
        "仕立て台(工芸職人の服)": { displayName: "仕立て台", recipe: "工芸職人の服_仕立て台", recipeLabel: "工芸職人の服", facility_multiplier: 1, item_value: 225, tools: "小刀全般" },
        "仕立て台(海賊の服)": { displayName: "仕立て台", recipe: "海賊の服_仕立て台", recipeLabel: "海賊の服", facility_multiplier: 1, item_value: 100, tools: "小刀全般" },
        "製紙場(小さな乾燥棚)": { displayName: "製紙場", recipe: "紙_製紙場", recipeLabel: "紙", facility_multiplier: 4, item_value: 5, tools: "no" },
        "製紙場(大きな乾燥棚)": { displayName: "製紙場", recipe: "紙_製紙場(大)", recipeLabel: "紙", facility_multiplier: 5, item_value: 5, tools: "no" },
        "酒場(水x2)": { displayName: "酒場", recipe: "酒場の主人(水x2)", recipeLabel: "酒場の主人(水x2)", facility_multiplier: 6, item_value: 1, tools: "no" },
        "酒場(水x1+アルコールを含まない飲料全般x1)": { displayName: "酒場", recipe: "酒場の主人(水x1+アルコールを含まない飲料全般x1)", recipeLabel: "酒場の主人(水x1+アルコールを含まない飲料全般x1)", facility_multiplier: 8, item_value: 1, tools: "no" },
        "酒場(水x1+アルコール飲料全般x1)": { displayName: "酒場", recipe: "酒場の主人(水x1+アルコール飲料全般x1)", recipeLabel: "酒場の主人(水x1+アルコール飲料全般x1)", facility_multiplier: 12, item_value: 1, tools: "no" },
        "鉱夫の仕事場(氷)": { displayName: "鉱夫の仕事場", recipe: "氷_鉱夫の仕事場", recipeLabel: "氷", facility_multiplier: 1, item_value: 4, tools: "つるはし全般" },
        "金敷(香炉)": { displayName: "金敷", recipe: "香炉_金敷", recipeLabel: "香炉", facility_multiplier: 1, item_value: 105, tools: "槌全般" },
        "木工作業台(避難民の被り物)": { displayName: "木工作業台", recipe: "避難民の被り物_木工作業台", recipeLabel: "避難民の被り物", facility_multiplier: 1, item_value: 22, tools: "no" },
        "仕立て台(避難民の被り物)": { displayName: "仕立て台", recipe: "避難民の被り物_仕立て台", recipeLabel: "避難民の被り物", facility_multiplier: 1, item_value: 22, tools: "no" },
        "木工作業台(竹玉)": { displayName: "木工作業台", recipe: "竹玉_木工作業台", recipeLabel: "竹玉", facility_multiplier: 1, item_value: 12, tools: "小刀全般" },
        "木工作業台(くし)": { displayName: "木工作業台", recipe: "くし_木工作業台", recipeLabel: "くし", facility_multiplier: 1, item_value: 43, tools: "彫刻刀" },
        "木工作業台(賽一式)": { displayName: "木工作業台", recipe: "賽一式_木工作業台", recipeLabel: "賽一式", facility_multiplier: 1, item_value: 50, tools: "彫刻刀" },
        "木工作業台(囲碁一式)": { displayName: "木工作業台", recipe: "囲碁一式_木工作業台", recipeLabel: "囲碁一式", facility_multiplier: 1, item_value: 75, tools: "彫刻刀" },
        "木工作業台(将棋一式)": { displayName: "木工作業台", recipe: "将棋一式_木工作業台", recipeLabel: "将棋一式", facility_multiplier: 1, item_value: 125, tools: "彫刻刀" },
        "木工作業台(双六一式)": { displayName: "木工作業台", recipe: "双六一式_木工作業台", recipeLabel: "双六一式", facility_multiplier: 1, item_value: 100, tools: "彫刻刀" },
        "木工作業台(小さな提燈)": { displayName: "木工作業台", recipe: "小さな提燈_木工作業台", recipeLabel: "小さな提燈", facility_multiplier: 1, item_value: 35, tools: "no" },
        "木工作業台(小さな行燈)": { displayName: "木工作業台", recipe: "小さな行燈_木工作業台", recipeLabel: "小さな行燈", facility_multiplier: 1, item_value: 35, tools: "no" },
        "木工作業台(円筒提燈)": { displayName: "木工作業台", recipe: "円筒提燈_木工作業台", recipeLabel: "円筒提燈", facility_multiplier: 1, item_value: 40, tools: "no" },
        "木工作業台(油の行燈)": { displayName: "木工作業台", recipe: "油の行燈_木工作業台", recipeLabel: "油の行燈", facility_multiplier: 1, item_value: 70, tools: "no" },
        "木工作業台(ろうそく:脂肪+藁)": { displayName: "木工作業台", recipe: "ろうそく_木工作業台", recipeLabel: "ろうそく(脂肪x1+藁x1)", facility_multiplier: 4, item_value: 12, tools: "no" },
        "木工作業台(ろうそく:蜜蝋+藁)": { displayName: "木工作業台", recipe: "ろうそく_木工作業台", recipeLabel: "ろうそく(蜜蝋x1+藁x1)", facility_multiplier: 6, item_value: 12, tools: "no" },
        "木工作業台(竹のろうそく:脂肪+竹)": { displayName: "木工作業台", recipe: "竹のろうそく_木工作業台", recipeLabel: "竹のろうそく(脂肪x1+竹x1)", facility_multiplier: 1, item_value: 8, tools: "no" },
        "木工作業台(竹のろうそく:蜜蝋+竹)": { displayName: "木工作業台", recipe: "竹のろうそく_木工作業台", recipeLabel: "竹のろうそく(蜜蝋x1+竹x1)", facility_multiplier: 1, item_value: 8, tools: "no" }
      }
    },
    "修繕": {
      facilities: {
        "陶芸窯(陶器)": { displayName: "陶芸窯", recipe: "陶器_陶芸窯", recipeLabel: "陶器", facility_multiplier: 1, item_value: 28, tools: "no" },
        "草の乾燥棚": { recipe: "藁_草の乾燥棚", recipeLabel: "藁", facility_multiplier: 1, item_value: 1, tools: "no" },
        "ヤシの葉の乾燥棚": { recipe: "藁_ヤシの葉の乾燥棚", recipeLabel: "藁", facility_multiplier: 3, item_value: 1, tools: "no" },
        "石工所": { recipe: "彫刻した石_石工所", recipeLabel: "彫刻した石", facility_multiplier: 1, item_value: 22, tools: "彫刻刀" },
        "鉱夫の仕事場(粘土)": { displayName: "鉱夫の仕事場", recipe: "粘土_鉱夫の仕事場", recipeLabel: "粘土", facility_multiplier: 1, item_value: 10, tools: "つるはし全般" },
        "大工作業台(板(針葉樹))": { displayName: "大工作業台", recipe: "板(針葉樹)_大工作業台", recipeLabel: "板(針葉樹)", facility_multiplier: 6, item_value: 4, tools: "釿全般" },
        "大工作業台(板(落葉樹))": { displayName: "大工作業台", recipe: "板(落葉樹)_大工作業台", recipeLabel: "板(落葉樹)", facility_multiplier: 6, item_value: 4, tools: "釿全般" },
        "大工作業台(板(上質な針葉樹))": { displayName: "大工作業台", recipe: "板(上質な針葉樹)_大工作業台", recipeLabel: "板(上質な針葉樹)", facility_multiplier: 6, item_value: 6, tools: "釿全般" },
        "大工作業台(板(上質な落葉樹))": { displayName: "大工作業台", recipe: "板(上質な落葉樹)_大工作業台", recipeLabel: "板(上質な落葉樹)", facility_multiplier: 6, item_value: 6, tools: "釿全般" },
        "大工作業台(板(果樹))": { displayName: "大工作業台", recipe: "板(果樹)_大工作業台", recipeLabel: "板(果樹)", facility_multiplier: 6, item_value: 9, tools: "釿全般" }
      }
    }
  }
};
